version: "1"
rules:
  - base: master
    upstream: google:master        # Required. Can be a branch in the same forked repo.
    mergeMethod: merge
    assignees:              # Optional
      - vesavlad
    reviewers:              # Optional
      - vesavlad
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - vesavlad
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
